language: node_js
node_js:
    - "10"
    
cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install -g vuepress

script:
  - npm run docs:build
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB__TOKEN  # Set in the settings page of your repository, as a secure
  target-branch: gh-pages
  local-dir: local_dir: docs/.vuepress/dist
  repo: KunoichiZ/PXR-Bot
  on:
    branch: master