language: node_js
node_js:
  - "node"
install:
  - npm install -g vuepress
script:
  - vuepress build && cd docs/.vuepress/dist && echo 'www.pxr-bot.kunoichiz.me' > CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
        branch: master
  local_dir: docs/.vuepress/dist
  repo: KunoichiZ/PXR-Bot
  keep-history: true
  target-branch: gh-pages